### PR TITLE
Avoid leaking goroutines on close

### LINKED ISSUE #92: What's the purpose of the 10 minute wait?
In the microservice I'm building, I've experienced a memory leak using the Kubernetes client-go package, which I traced back to https://github.com/moby/spdystream/blob/master/connection.go#L733.

The memory leak is really well documented in https://github.com/kubernetes/kubernetes/issues/105830.

Essentially what happens is that running the stream executors with in-cluster kubeconfig context leads to many broken pipes, which leads to the waiting time of 10 minutes before the shutdown goroutine ends. This waiting time keeps the data in memory alive. Not a big deal if it's a small number of broken pipes, but in my case the number is rising very quickly and easily can reach 2-3 GB of allocated memory within the 10-minute hold, thus considering it a memory leak of high significance (essentially a system-service pod is taking memory that the users of the cluster can't use).

The fix for this is that I replaced the waiting time from 10 minutes to 10 milliseconds instead, and the memory leak is "gone"(not truly gone, just very low and GCed quickly). However, I wonder what are the repercussions of changing https://github.com/moby/spdystream/blob/master/connection.go#L733 to milliseconds? Also, what is the point of waiting here in the first place?

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #92 

* Avoids leaking timers in shutdown and Wait if the functions exit before the timeouts expire
* Shortens the timeout for an unhandled error from 10 minutes to 1 second. It looks like the 10 minute timeout was added in https://github.com/moby/spdystream/issues/24 / https://github.com/moby/spdystream/pull/25 without a rationale... happy to adjust this PR if there are other things aspects to consider. The paths where errors _could_ be handled are:
   1. client calls CloseWait(). We know Close() is immediately followed by Wait(), a second seems entirely sufficient.
   2. client calls Close() followed by Wait(). We don't control the calls, but the expectation is that Close() is _immediately_ followed by Wait(), so a second seems entirely sufficient.
   3. client calls NotifyClose(), GOAWAYFRAME notifies lastStreamChan, client responds by calling Wait(). lastStreamChan is notified before the shutdown is begun, which gives the caller a second to call Wait() if they want to handle the shutdown error. This is the only path I don't have a great intuition of, but a second to process the channel notification seems reasonable. I also can't find a single use of this function in a [public github search](https://github.com/search?q=%2F%5C.NotifyClose%5C%28%5B%5E%29%5D%2F+language%3AGo++-path%3Atest+NOT+amqp&type=code).

### CODE REVIEW

**Comment by liggitt** [comment]
cc @dims @aojea

File: connection.go [hunk 1]
```diff
@@ -712,7 +712,9 @@ func (s *Connection) shutdown(closeTimeout time.Duration) {
 
 	var timeout <-chan time.Time
 	if closeTimeout > time.Duration(0) {
-		timeout = time.After(closeTimeout)
```
Comment (aojea) [inline connection.go:715]: reference https://arangodb.com/2020/09/a-story-of-a-memory-leak-in-go-how-to-properly-use-time-after/

File: connection.go [hunk 2]
```diff
@@ -739,7 +741,15 @@ func (s *Connection) shutdown(closeTimeout time.Duration) {
 	}
 
 	if err != nil {
```
Comment (aojea) [inline connection.go:743]: so, at this point we now the underly connection was close, there is no longer a TCP stream because s.conn.Close() and all streams were closed

Comment (aojea) [reply connection.go:743]: These waits for the shutdownChan to be drained, that can be done with the CloseWait() and Wait() methods, if this is not handled we just bail out. So effectively this is waiting for those two methods to be called.

The only way I can see this can not be handled is:
1. We call Close() directly
2. we receive a goaway frame

so the users need to invoke the Wait() method to handle this situation

Comment (aojea) [reply connection.go:743]: I'm just stating my understanding that matches the one in Jordan's description of the issue.

File: connection.go (hunk 1 above)
Comment (dims) [reply connection.go:715]: ACK

File: connection.go (hunk 2 above)
Comment (dims) [reply connection.go:743]: thanks @aojea

**Review by dims — APPROVED** [review]
LGTM

**Comment by dims** [comment]
@thaJeztah ok to merge and cut a tag with this change?

**Review by dmcgowan — APPROVED** [review]

**Comment by dims** [comment]
thanks @dmcgowan
